const JSON_HEADERS={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
function send(res,status,body){res.status(status);Object.entries(JSON_HEADERS).forEach(([k,v])=>res.setHeader(k,v));return res.json(body)}
function cleanText(v){return typeof v==="string"?v.trim():""}
function normalizeDomain(v){return cleanText(v).toLowerCase().replace(/^https?:\/\//,"").replace(/\/.*$/,"").replace(/\.$/,"")}
function validDomain(d){return /^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i.test(d||"")}
function cleanSlug(v){return cleanText(v).toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-+|-+$/g,"").replace(/-{2,}/g,"").slice(0,63)}
function env(name,required=true){const v=cleanText(process.env[name]);if(required&&!v)throw new Error(`Missing required environment variable: ${name}`);return v}
function teamQuery(){const id=env("VERCEL_TEAM_ID",false);return id?`?teamId=${encodeURIComponent(id)}`:""}
async function vercelRequest(path,options={}){const r=await fetch(`https://api.vercel.com${path}`,{...options,headers:{Authorization:`Bearer ${env("VERCEL_TOKEN")}`,"Content-Type":"application/json",...(options.headers||{})}});const p=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(p.error?.message||p.message||`Vercel request failed (${r.status}).`);e.status=r.status;e.payload=p;throw e}return p}
function domainsPath(domain=""){const id=encodeURIComponent(env("VERCEL_PROJECT_ID"));return `/v10/projects/${id}/domains${domain?`/${encodeURIComponent(domain)}`:""}${teamQuery()}`}
async function addDomainToVercel(domain){try{return await vercelRequest(domainsPath(),{method:"POST",body:JSON.stringify({name:domain})})}catch(e){if(e.status===409)return getVercelProjectDomain(domain);throw e}}
async function getVercelProjectDomain(domain){return vercelRequest(domainsPath(domain),{method:"GET"})}
async function verifyVercelProjectDomain(domain){const id=encodeURIComponent(env("VERCEL_PROJECT_ID"));return vercelRequest(`/v9/projects/${id}/domains/${encodeURIComponent(domain)}/verify${teamQuery()}`,{method:"POST",body:"{}"})}
async function removeDomainFromVercel(domain){return vercelRequest(domainsPath(domain),{method:"DELETE"})}
function dnsRecordsFor(domain,data={}){const apex=domain.split(".").length===2;const records=apex?[{type:"A",name:"@",value:"76.76.21.21"},{type:"CNAME",name:"www",value:"cname.vercel-dns.com"}]:[{type:"CNAME",name:domain.split(".")[0],value:"cname.vercel-dns.com"}];const v=Array.isArray(data.verification)?data.verification[0]:null;return{records,verification_record:v?{type:v.type||"TXT",name:v.domain||v.name||`_vercel.${domain}`,value:v.value||""}:null}}
function statusFromVercel(data={}){const verified=data.verified===true||data.verification?.length===0||data.misconfigured===false;const connected=verified&&data.misconfigured!==true;return{domain_status:connected?"connected":"verifying",dns_verified:connected,ssl_status:connected?"active":"provisioning"}}
async function supabaseRequest(path,options={}){const url=env("SUPABASE_URL").replace(/\/$/,"");const key=env("SUPABASE_SERVICE_ROLE_KEY");const r=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:options.prefer||"return=representation",...(options.headers||{})}});const p=await r.json().catch(()=>null);if(!r.ok){const e=new Error(p?.message||p?.hint||`Database request failed (${r.status}).`);e.status=r.status;e.payload=p;throw e}return p}
async function authenticatedUser(req){const h=cleanText(req.headers.authorization);const token=h.startsWith("Bearer ")?h.slice(7).trim():"";if(!token){const e=new Error("Authentication required.");e.status=401;throw e}const r=await fetch(`${env("SUPABASE_URL").replace(/\/$/,"")}/auth/v1/user`,{headers:{apikey:env("SUPABASE_ANON_KEY"),Authorization:`Bearer ${token}`}});const u=await r.json().catch(()=>({}));if(!r.ok||!u?.id){const e=new Error("Your session is invalid or expired.");e.status=401;throw e}return u}
const SELECT="id,user_id,name,slug,published,published_url,custom_domain,domain_status,ssl_status,verified_at,dns_verified,domain_last_checked_at,domain_error,dns_records,verification_record";
async function getOwnedProject(id,owner){const rows=await supabaseRequest(`website_projects?id=eq.${encodeURIComponent(id)}&user_id=eq.${encodeURIComponent(owner)}&select=${SELECT}`,{method:"GET"});const p=Array.isArray(rows)?rows[0]:null;if(!p){const e=new Error("Website project not found.");e.status=404;throw e}return p}
async function listOwnedProjects(owner){return supabaseRequest(`website_projects?user_id=eq.${encodeURIComponent(owner)}&select=${SELECT}&order=updated_at.desc`,{method:"GET"})}
async function updateProject(id,owner,patch){const rows=await supabaseRequest(`website_projects?id=eq.${encodeURIComponent(id)}&user_id=eq.${encodeURIComponent(owner)}`,{method:"PATCH",body:JSON.stringify(patch),prefer:"return=representation"});return Array.isArray(rows)?rows[0]:rows}
async function slugTaken(slug,excludeId=""){let q=`website_projects?slug=eq.${encodeURIComponent(slug)}&select=id&limit=1`;if(excludeId)q+=`&id=neq.${encodeURIComponent(excludeId)}`;const rows=await supabaseRequest(q,{method:"GET"});return Array.isArray(rows)&&rows.length>0}
function errorResponse(res,e){console.error("Bluvixa domain API error:",e);return send(res,e.status||500,{error:e.message||"Unexpected domain service error."})}
module.exports={send,normalizeDomain,validDomain,cleanSlug,addDomainToVercel,getVercelProjectDomain,verifyVercelProjectDomain,removeDomainFromVercel,dnsRecordsFor,statusFromVercel,authenticatedUser,getOwnedProject,listOwnedProjects,updateProject,slugTaken,errorResponse};
